### 测试登录
POST http://localhost:8001/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### 测试登录用户
GET http://localhost:8002/auth-client-demo/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjkzNzM3NDgyLCJleHAiOjE2OTM3NTU0ODJ9.RCY6y1iqYknHB78jY6XYAa9Jf57Gy80Hu9RC8KHDNIkNDbeJ_qOnyMsFsAK8kFr5u5ivJTvzDWkOOyOIUKZ4lzuUMJZCQV3lMYeOgB4WvemuUqzVnMjbs4PNBlz_8q5Wy1_okWyoy39OnNSlHgPMnhN-anZzYwvXH5P2OQEHq3fw9yZ3eodr2GvGrEH959u-iOoAiSPYIYsGnke1fl-FJor9dDBfeO3xO3aPd4cEksOiO1l9Q4FTbp9hG8zVoHuGuhcsndtY4JDml1ogLSknQYGHl8px59QM-go1Yq0thgxhidmPkzB9Xsz6MQy-a-mMK90Ihg44KPoAYDcq-wuWMwoW8ZAUDaipkPCBVTDEi5Ypatejc6id7AYpqA3nGJK3D-ma3TMP2SP6Uo9KdWxaYFc_sFKTUv0qsK7LSoWrBsefQeqMdm04dZKzODxkNy__TL7GcW4xbZuipazU2L_KqAHuBBEPSOsRBSbXeXe6rHFLzlDPMYF2S-sxLsN1j7hp5f3iiy5XZo4fmnNrgen9iBKorMGmnNhw7IysuUinkXWbQw0qi9BElCp1YxY39-xyOVMcU1bsEsow_0F_SqiwYeilzgp3JRri4VH55hb4P0K1hTc7aRAW2JfPvTKM0dbCh7r-WPa7V4SWKw-FnIX_rvjg0dtkIsjlg2LAk8AAHNE

