### 账号密码登录
POST http://127.0.0.1:8080/api/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 获取登录用户(auth)
GET http://localhost:8080/api/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket # 校验
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiI5NTMwMTM4MTM4OGY0NjdkOGFmYzE3N2I0NmMyMDRiZCIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJpYXQiOjE3MjE5NjMwNzYsImV4cCI6MTcyMTk3MDI3Niwibmlja05hbWUiOiLnjovlpKflrrgiLCJ1c2VyVHlwZSI6Ik1FIiwidXNlcklkIjoiMSIsInVzZXJuYW1lIjoiYWRtaW4ifQ.FVYl_6bzMOPjaIADcTId0JPAH4JVkfFOeLCf0ZYiQJIkXMUxsVVLsqqjhaT5shejp40HfMLQT3YPamG8yjMYCXuDKkQ97oqTnfuq5expHjFQRiVvSpoTr1aTLj_vM20FlMck_jpGGbN9sOHA18LWQC8WFZ21ZYwhOf8v_BVlC1vnG5MfZohkR0VbsPzqHJfFmKvh40EVPMsnOAo-9hLqYeVEDaGb5Lgo-Fqwqx6X43uLErGrgTx98eOACLknGUxdtE1Z8yD0-TrV71z9Xs_MI2cIZfr1tTb6CcxhkImSUiJ7lK8E0o9Xku-bZpevTXI6RhnLLrdmCuuC_qHml_jYFu6HTUrknwJR4m8T5Xi1UJXV2y1nFV-vR1Kpxd7it2ypGnCRHzotMp93nKulVA7xP3A9xT9qQekvZBg0mbpWu5BLLpYU5onY43MAyy7-vGL9pKJUSZFOXDbKyaRHLzSsgfXETYEOT1vZ3e8rOcokSZ3AtEmOLB-oj6fjRSIMp32fDoKaGKhVjukrYrCVAGgweG8v94jrBzQU6pHb0vtVrYSN6uudho86YUNVcTnvgVx_ZR59LLLdvq3vmP7N7atzhwhNhcfQ1VemijQB_ZGjmn9QABT31DdL7SF_gIhYA7hpK3RjLahifNFcZ9nEPJMCn72AAFx7YKOrPxSLiBvCDsc


### 获取登录用户(auth-client-demo)
GET http://localhost:8080/api/auth-client-demo/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjkzNzQ3MDE1LCJleHAiOjE2OTM3NTQyMTV9.sxvm_bs4WC5H6DRPhcpmZ9DW2O5Qe0JS9M2XSnBc_ZoJeIKQb4-RKy8fqVyn727c5SDH2LAr-DGhJndw3m_2XA6_YMrr5r8_aXJaBipVbXECaDa7ZnmhiUOBEF7vqJBvIRAwJKcAqtClvl7lbYllihf3VnaiAI8zVMGdMqVYtYrazM5MnQN5YEVpP7RB-z5NzmxhBzII1rvcGP-6GwDKSx4lh-N8gaupcCgnMfeyNI_s_0O1rJRq5AX09OHnPriv6y8iB1kA1VHdBUYRp5GMJBegkiL6g-2W8I7qyxbAamKYTbHNmYCHow0GnlcDMMu-V6Gdikv9hdzlXJ_tukGejRb145vuchTA6WIxJ6b7fUxyhujigjRn6femUsFT7r2csR_Efq52i-KoPSpSME7tfITzfRa5Qvwl1W6JrC_sj7MHWNV8T2eiia-AWlZOj_J7m6He4NSWvNrRhyTtCkpMHvpGqckP4alYfu8sN2NN8S4ohC8vhh3U6IYE3BxLCAOopP_UyKw4aIhbaRQdUnVR-HuWq-uYVLTZ9Zq2GxI1Xs2CNhoTOn7ON5lvMbv9xmkW60hB__bx9n8CZHtTiwVKvoH6qNta5yTxxJFhM9QHlc2lI7El2Guil4nf6SrZwNi92I6-fn2qKzNOMkDuUf707pkRdpNe9Xfs4Uj_0wMPN4g

