### 账号密码登录
POST http://localhost:8080/api/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 获取登录用户(auth)
GET http://localhost:8080/api/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket # 校验
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjkwNzkxMDA1LCJleHAiOjE2OTA4MDkwMDV9.jFBYpUGxNoeo341e3WhFWput-AZHED3NXEwdRJMtvejKf86vwyFJ51IFUsLzAotPBtg2RBIu1lhMAW3G2GZz8ED1sreGqYBli8M-iYTkFGh_8m7URU5ltX52oM4t0IXIy7ANW1NO9mG0rIVLQRiENB4h8D7xIa5g-IHbak6klSsHMR41PT6eTALXgbMbfc__BK2sip7IRq5ODzdMpvO62jihjK7BFYA7adMBJR6VNZmAVRORqAEzJkCGPQ1O-0cpOi8C3bloSg-yhoAS0SfqsfaxGmg_Hynoi3NSINnLjh7ImiZWSmQ8OgQMX1YmzAhuuFMZBF3l3LpvWjQE4TBefl9PM5tNuTdWm-BIa-bLM3K_5lduzcPRoyxvbmAF-kHKnbbNtEt_Ipx457bRBFWLhzsTqqqOTjrSt22wTTWiiH2WmwfEQfVecDap_unnkeQJk5-a1zbKKCyt6I087JhYa-x9DBpiCvbpEMxxjz5cTeNip_TzBhQSkYtCQhO2IW6S8y8P5DD4lle15_Qj2HJzttEt5hJIR1IF49eKodLDVm99-BS0hJVGw3TMLZ2LtXr9cKA8j6l2-h-mJ3B5WJQR2vvnhdAcnSOW5n1VqsU68KlQdyBrbmll7TbiLHKQwe4mDlQjupEdF_NvVfaL1CSoPjo2CNAwSeIZ1r6B0oANqd0


### 获取登录用户(admin)
GET http://localhost:8080/api/admin/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjkwNzkxMDA1LCJleHAiOjE2OTA4MDkwMDV9.jFBYpUGxNoeo341e3WhFWput-AZHED3NXEwdRJMtvejKf86vwyFJ51IFUsLzAotPBtg2RBIu1lhMAW3G2GZz8ED1sreGqYBli8M-iYTkFGh_8m7URU5ltX52oM4t0IXIy7ANW1NO9mG0rIVLQRiENB4h8D7xIa5g-IHbak6klSsHMR41PT6eTALXgbMbfc__BK2sip7IRq5ODzdMpvO62jihjK7BFYA7adMBJR6VNZmAVRORqAEzJkCGPQ1O-0cpOi8C3bloSg-yhoAS0SfqsfaxGmg_Hynoi3NSINnLjh7ImiZWSmQ8OgQMX1YmzAhuuFMZBF3l3LpvWjQE4TBefl9PM5tNuTdWm-BIa-bLM3K_5lduzcPRoyxvbmAF-kHKnbbNtEt_Ipx457bRBFWLhzsTqqqOTjrSt22wTTWiiH2WmwfEQfVecDap_unnkeQJk5-a1zbKKCyt6I087JhYa-x9DBpiCvbpEMxxjz5cTeNip_TzBhQSkYtCQhO2IW6S8y8P5DD4lle15_Qj2HJzttEt5hJIR1IF49eKodLDVm99-BS0hJVGw3TMLZ2LtXr9cKA8j6l2-h-mJ3B5WJQR2vvnhdAcnSOW5n1VqsU68KlQdyBrbmll7TbiLHKQwe4mDlQjupEdF_NvVfaL1CSoPjo2CNAwSeIZ1r6B0oANqd0

