### 账号密码登录
POST http://localhost:8080/api/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 获取登录用户(auth)
GET http://localhost:8080/api/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket # 校验
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjgzMjg5NjU2LCJleHAiOjE2ODMzMDc2NTZ9.AfH6LAqMXmACLllzPxg6uViQD04UQAh7ZSHskofnkkBuf-WtaLMQaQq0o6cuxaSgfyHViWxlESEy3RwvxjpP-KJ5XsEqSD3O0jpGKqcEZTaV1gCooGmIlWf6f9WEAaUil-xTIkKQqBDlEPMQDz_TDkjyh1Qzh9o9vJXhoycKwKtUO8RJ8_HoFhCsrYVNEwdDwLFIoc3xjajIOyu8Y42JPWyhbQsIsNnKIRZxukhteORlV2yXa_y-UoV3abJY1aO01kSlXwQzRsWLpUnKYWOEBNHrWnBAlr4URNnmfHYZrqXpE2o8RmpgJnJnycuIzUXSEe3kas1nWQLqv8nNMi6iqeysie4ZfoWedez2wCQtk7nGslkChPuMt2Jc0BIuKajNDCwX0YtntLIIGmsrfZGG7_UGFP5z9yldqp9KPrx7zxQjq1x3ZmSZuKfUXwRQQD-p_NIFGa3GJ-8zEM4MTTSkv4K0p3l7_Sl91YgylYxHgmtybCjpVtEcA3fU-i4Uys_Lb8dcNncXrEbRwqprhbtmvCULRNS-5e_Xr8Cls8tscKMFOfT_sKypeRmYYywrOOEjBLWxH2Y8dx6pZ5XHUYatUM1BjpvjFp5rikSkH0V2XwtFWNj5mHH0Scykk4Msk_qp6z30ds-LlaaQyWuOPDQDA-Nksoy6N0T2HGGjJs0ZwTM


### 获取登录用户(admin)
GET http://localhost:8080/api/admin/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjgzMzYxNzk0LCJleHAiOjE2ODMzNzk3OTR9.Saq3p5F0H2COobFGEQxCdhlhfYNzd5dtnyBnjyb8JVyRz4sMPIMlYtpz-uwC4lStv1jRyC9B4fnOCI-6X9K10R5rrxlfZzzUu2YX2aDGKWZyFV8lUlyU6UY3Ft_3SvXABJ1XJmEvMr2qSt3uiRB2jNz_CEcFptaMHKB5EF3SNb1q2KnJRwZxqx3fDENvBFCdeNXl8DzGLHKY1SwdduYMEHV5hcYjhNebodEpdGImvufRdxrRl0NM4LxlPIVdY6u9vtWG_YJdhTk3A2ZTOKh7rAKE0SyUEMqxls9PDorFs4HaqGHVdKPhyibdNf4pCe1CGzrZYQkPw-tH-Hl40sja2CSz1L_FIQFKMNvZ-1hfeutXFSHD9YgLl3ylMDNvjnOZsz9QVELMz8RL9pS4Ylm_WZjwxMqgRaVfZ2_59C9yGoaFH7Z-NKqYe2WCxxNH8wIL5FuaIH6SZ-kB-gHpg1AktdsPuMN9_aV8c2CI-n3ypED2c5w8aBuzngVvsiBXa_0FLlol_Orsa8p-gNMTFGy5Ib1aKQxm-8c0JHPLWcsNN0dTDoAMpEaovvspNGXX1yvZ8kbzBqtn8HMcqI1dvoJnr6vUEp-LfGDHaLw-fMepaSNKFRo0JFl7GDqbAh9gnyLf32UGme6nmk9YTABvuVSfgfds4VNKr4ByiHzZynUBGYY

