# 日志配置
logging:
  config: classpath:fly-cloud.xml
  level:
    cn.jay.repository: trace

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    loadbalancer:
      # 重试策略
      retry:
        maxRetriesOnSameServiceInstance: 0
        maxRetriesOnNextServiceInstance: 0
      clients:
        service-product:
          retry:
            maxRetriesOnSameServiceInstance: 0
            maxRetriesOnNextServiceInstance: 0
    #    inetutils:
    #      preferred-networks: 127.0.0.1
    ## 向 nacos 发起注册
    nacos:
      discovery:
        username: nacos
        password: nacos
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: 127.0.0.1:8848
        namespace: 07656b3c-bb69-470a-a942-6ae27b5287cb
        group: DEFAULT_GROUP
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator