# 日志配置
logging:
  config: classpath:fly-gateway.xml
  level:
    cn.jay.repository: trace

# 认证中心配置
auth:
  serviceId: auth
  client:
    id: ${spring.application.name}
    secret: 123456

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    web-application-type: reactive
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    # sentinel 限流配置
    sentinel:
      transport:
        port: ${server.port}
        dashboard: localhost:8888
      scg:
        fallback:
          mode: response
          response-status: 500
          response-body: '{"status": 500,"success": false, "msg": "网关流量超量！", data: null}'
    loadbalancer:
      cache:
        ttl: 5s
    gateway:
      globalcors:
        cors-configurations: # 跨域配置
          '[/**]': # 匹配所有路径
            allowed-origins: # 允许的域名
              - "http://localhost:7080"
            allowed-headers: "*" # 允许的请求头
            allowed-methods: "*" # 允许的方法
            allow-credentials: true # 是否携带cookie
      httpclient:
        pool:
          max-connections: 500
          max-idle-time: 10000
    ## 向 nacos 发起注册
    nacos:
      discovery:
        username: nacos
        password: nacos
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 07656b3c-bb69-470a-a942-6ae27b5287cb
        group: DEFAULT_GROUP
        metadata:
          management:
            # 网关没有配置上下文
            context-path: /actuator
          preserved:
            heart:
              beat:
                interval: 3000
                timeout: 3000
            ip:
              delete:

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

# 认证中心配置
fly:
  cloud:
    auth:
      token:
        type: RSA
      app:
        service-id: auth
        app-id: ${spring.application.name}
        app-secret: 123456
        matchers:
          - /oauth/jwt/**
    ## 网关配置
    gateway:
      ### 动态获取 nacos 中的路由配置
      routes:
        serverAddr: 127.0.0.1:8848
        namespace: b6783835-a27f-4ec3-b9ee-05bfa917e812
        dataId: GATEWAY_ROUTES
        group: GATEWAY_ROUTES
      ### 配置网关不拦截路径前缀, 不需要权限认证等
      ignore:
        matchers:
          - /auth/oauth/access_token
          - /auth/oauth/token
          - /api/actuator
          - /actuator
          - /admin/open/dict
          - /oss
          - /oss/upload
          - /flexible/login
          - /flexible/authentication/form