# 日志配置
logging:
  config: classpath:fly-cloud.xml
  level:
    cn.jay.repository: trace
#  file:
#    name: boot.log
#  pattern:
#    ####日志高亮
#    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50


spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 登录账号和密码配置
  security:
    user:
      name: admin
      password: 123456

  cloud:
    nacos:
      username: admin
      password: 123456
      discovery:
        username: nacos
        password: nacos
        watch-delay: 3000
        watch:
          enabled: true
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 07656b3c-bb69-470a-a942-6ae27b5287cb
        group: DEFAULT_GROUP
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
          user.name: ${spring.security.user.name}
          user.password: ${spring.security.user.password}

  ## thymeleaf 邮件发送模板设置
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: utf-8
    check-template: false
    check-template-location: false
