### 测试登录
POST http://localhost:8001/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### 测试登录
POST http://localhost:8001/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 测试登录用户(auth)
GET http://localhost:8001/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJmNDRlMTEyY2Y2MWU0NjYwOWRkYjcwYTg1NWM3ZjM3YSIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJpYXQiOjE3MTc1OTMzODQsImV4cCI6MTcxNzYwMDU4NCwibmlja05hbWUiOiLnjovlpKflrrgiLCJ1c2VyVHlwZSI6Ik1FIiwidXNlcklkIjoiMSIsInVzZXJuYW1lIjoiYWRtaW4ifQ.Oc6TS0JHUjmX5s9GqP7EyCsyT5aNulKFTeSWPgzhDUmZyjODuVbH9QMP3ac4k01CTHBLYbpV6Yp3p1JatFSu060gvx_PeMOXocbIu2PvibmJnXig8wgimHA76ViW5mb2txNZO6cq0o5HUrmR_64pDyoM-3hQEJNlvZdZ53cX2CcXpE58F9JrnZIGvlghuY9NcdtEGCLmbiAl-OqvPY08QFyloEtlyYKY2XVteiFko-khKag5NdLV7k5ZUoJCNvXMQ4UOnoWrwbVhlf7HHpnlmijpRMiRwpr7dzIqeEK5wvx5qwnF_uffP9idexTfvJZysaJfj9mGgciTOx_GNE5UNtaNS3t_FEPpeEkVzlplGG3X4o20i9WB-lHRlIN1JwBBC82IiOrZDO784f4Zq7pkdwL0ljKl8orausbKM6nA_k2bBY2yAiFlmybhwpMTY2lkX0Oer9DuHgfaXp2MoHxggDjyPxkSUA6Lgdb8lP0QNIFffD7nEmXl8_tDD09CgIpH08gkuFEBuSqAF9ITW6dVpzjKXHDGutoojB9JSbmITrPKteu1WwMKMLwqD71s-T8fyJhqWivV3S4LiYPDi7V8B9k1D3WBn8xtpph6JPajkijO55fSXPRxEBu4dGrss47IbjBI9S1hOgFhEo-xdc0DRV4zcy-8SKQHoyhU9sFLYww

### 测试登录用户(admin)
GET http://localhost:8002/admin/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJmNDRlMTEyY2Y2MWU0NjYwOWRkYjcwYTg1NWM3ZjM3YSIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJpYXQiOjE3MTc1OTMzODQsImV4cCI6MTcxNzYwMDU4NCwibmlja05hbWUiOiLnjovlpKflrrgiLCJ1c2VyVHlwZSI6Ik1FIiwidXNlcklkIjoiMSIsInVzZXJuYW1lIjoiYWRtaW4ifQ.Oc6TS0JHUjmX5s9GqP7EyCsyT5aNulKFTeSWPgzhDUmZyjODuVbH9QMP3ac4k01CTHBLYbpV6Yp3p1JatFSu060gvx_PeMOXocbIu2PvibmJnXig8wgimHA76ViW5mb2txNZO6cq0o5HUrmR_64pDyoM-3hQEJNlvZdZ53cX2CcXpE58F9JrnZIGvlghuY9NcdtEGCLmbiAl-OqvPY08QFyloEtlyYKY2XVteiFko-khKag5NdLV7k5ZUoJCNvXMQ4UOnoWrwbVhlf7HHpnlmijpRMiRwpr7dzIqeEK5wvx5qwnF_uffP9idexTfvJZysaJfj9mGgciTOx_GNE5UNtaNS3t_FEPpeEkVzlplGG3X4o20i9WB-lHRlIN1JwBBC82IiOrZDO784f4Zq7pkdwL0ljKl8orausbKM6nA_k2bBY2yAiFlmybhwpMTY2lkX0Oer9DuHgfaXp2MoHxggDjyPxkSUA6Lgdb8lP0QNIFffD7nEmXl8_tDD09CgIpH08gkuFEBuSqAF9ITW6dVpzjKXHDGutoojB9JSbmITrPKteu1WwMKMLwqD71s-T8fyJhqWivV3S4LiYPDi7V8B9k1D3WBn8xtpph6JPajkijO55fSXPRxEBu4dGrss47IbjBI9S1hOgFhEo-xdc0DRV4zcy-8SKQHoyhU9sFLYww

