### 测试登录
POST http://localhost:8001/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 测试登录用户(auth)
GET http://localhost:8001/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJlYjNiOWZiNzAwOGQ0MTRmYTQ3ZTg0ZTNiNDVlZmQ3YyIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJpYXQiOjE3MTc1NzU5MjYsImV4cCI6MTcxNzU4MzEyNiwibmlja05hbWUiOiLnjovlpKflrrgiLCJ1c2VyVHlwZSI6Ik1FIiwidXNlcklkIjoiMSIsInVzZXJuYW1lIjoiYWRtaW4ifQ.vwgGoY0I6A0RnmM0eCrHaX-KzmoTNbm91_vNuNsu8-Gd1lCwQLDuqSIe_qc-yQorocXIQqZVwSK5hxBRg-EO2Q0Uj6RCW5LzBplllipLnsRoV1gzLBGL5NWyR3Y_Sa07Mz6imaMTq4wjVHr13VZQn_C0NQTTtD9YJidQ3RmS0arVUzb_PiKH6TKY1M-kuSzPYRjWzkaXHcD4dDW1J0atuZg55xiGEKMVSCK1uBnb8Y-fNKI33T9nxqhkkfAlYl5dd5xRr_N_KjFUp6T7-0jdEuYlWgp1XGdjavuw3T9_wl5FydwnJog9yCNbGdgnRjw9XR-bVrVs-PvsWM7QpBrlfLjv7WSrX62QJP5mhAnF0V0Eo8j_GDfPhSDoXJGPpBYqBTFRysy5bKFyO3RMtyBiitzhbxJe8vUUp117mkGU_R0K14kVyHvSGv5oTckHnxpi2wBjdhoQZDCwfJHf2ZiAdEnIyuelQ1Bya9C-W2Zueb2PvlC8vlyGnQR0_IiVNgQT_1glqzDOl_iJHIXlyGKnDrVrWRJLPVQWz_bn4j1hJHRFpLkaOYAlbbmQCeQN2FQkCiRe22CZTPGCrqTKgMIzVm0WlcRBJiUldaWFgyTQQhKOotnZRQw30uBoS6aNGWnKfyNuJY9o7rHfYDggix_z7cAswN2KLJ117piC1L12gqk

### 测试登录用户(admin)
GET http://localhost:8002/admin/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJlYjNiOWZiNzAwOGQ0MTRmYTQ3ZTg0ZTNiNDVlZmQ3YyIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJpYXQiOjE3MTc1NzU5MjYsImV4cCI6MTcxNzU4MzEyNiwibmlja05hbWUiOiLnjovlpKflrrgiLCJ1c2VyVHlwZSI6Ik1FIiwidXNlcklkIjoiMSIsInVzZXJuYW1lIjoiYWRtaW4ifQ.vwgGoY0I6A0RnmM0eCrHaX-KzmoTNbm91_vNuNsu8-Gd1lCwQLDuqSIe_qc-yQorocXIQqZVwSK5hxBRg-EO2Q0Uj6RCW5LzBplllipLnsRoV1gzLBGL5NWyR3Y_Sa07Mz6imaMTq4wjVHr13VZQn_C0NQTTtD9YJidQ3RmS0arVUzb_PiKH6TKY1M-kuSzPYRjWzkaXHcD4dDW1J0atuZg55xiGEKMVSCK1uBnb8Y-fNKI33T9nxqhkkfAlYl5dd5xRr_N_KjFUp6T7-0jdEuYlWgp1XGdjavuw3T9_wl5FydwnJog9yCNbGdgnRjw9XR-bVrVs-PvsWM7QpBrlfLjv7WSrX62QJP5mhAnF0V0Eo8j_GDfPhSDoXJGPpBYqBTFRysy5bKFyO3RMtyBiitzhbxJe8vUUp117mkGU_R0K14kVyHvSGv5oTckHnxpi2wBjdhoQZDCwfJHf2ZiAdEnIyuelQ1Bya9C-W2Zueb2PvlC8vlyGnQR0_IiVNgQT_1glqzDOl_iJHIXlyGKnDrVrWRJLPVQWz_bn4j1hJHRFpLkaOYAlbbmQCeQN2FQkCiRe22CZTPGCrqTKgMIzVm0WlcRBJiUldaWFgyTQQhKOotnZRQw30uBoS6aNGWnKfyNuJY9o7rHfYDggix_z7cAswN2KLJ117piC1L12gqk

