### 测试登录
POST http://localhost:8001/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 测试登录用户
GET http://localhost:8001/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjgzMjg5NjU2LCJleHAiOjE2ODMzMDc2NTZ9.AfH6LAqMXmACLllzPxg6uViQD04UQAh7ZSHskofnkkBuf-WtaLMQaQq0o6cuxaSgfyHViWxlESEy3RwvxjpP-KJ5XsEqSD3O0jpGKqcEZTaV1gCooGmIlWf6f9WEAaUil-xTIkKQqBDlEPMQDz_TDkjyh1Qzh9o9vJXhoycKwKtUO8RJ8_HoFhCsrYVNEwdDwLFIoc3xjajIOyu8Y42JPWyhbQsIsNnKIRZxukhteORlV2yXa_y-UoV3abJY1aO01kSlXwQzRsWLpUnKYWOEBNHrWnBAlr4URNnmfHYZrqXpE2o8RmpgJnJnycuIzUXSEe3kas1nWQLqv8nNMi6iqeysie4ZfoWedez2wCQtk7nGslkChPuMt2Jc0BIuKajNDCwX0YtntLIIGmsrfZGG7_UGFP5z9yldqp9KPrx7zxQjq1x3ZmSZuKfUXwRQQD-p_NIFGa3GJ-8zEM4MTTSkv4K0p3l7_Sl91YgylYxHgmtybCjpVtEcA3fU-i4Uys_Lb8dcNncXrEbRwqprhbtmvCULRNS-5e_Xr8Cls8tscKMFOfT_sKypeRmYYywrOOEjBLWxH2Y8dx6pZ5XHUYatUM1BjpvjFp5rikSkH0V2XwtFWNj5mHH0Scykk4Msk_qp6z30ds-LlaaQyWuOPDQDA-Nksoy6N0T2HGGjJs0ZwTM

