### 测试登录
POST http://localhost:8001/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 测试登录用户
GET http://localhost:8001/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjg5NDM0OTY4LCJleHAiOjE2ODk0NTI5Njh9.ptaHdhxbA4b5rgbX9CsFak4NbvmiClleWHXI5kgcSc4cxPNLWUfmEs6fnD_xs3of1yp9xEZRg4G9xee3MhODGtJxSnXAtO9Ar5hFRJM_qlyuDx5qMHolxF0RmYabmzpUziQoXlT4_xxD3ka0Fxnm9eDmRTXTf7XBiFbxT1DSSPGzJqNYf9kll4u71dNL8vE_RMwQ8E-VUkT2aMUVbSIPIpxOK5HRaYVUX8pTsWkjNPBf3Ryi5p0Av0vu4FS9kfh8w32e74wckCorvZ_sQaSKjGr1ZWSUlteKwQXBTLmfwnJUGAjvS68g9jiKV_fbjyo0-K5czz7Rez7-0oFjFk6EXUdSD6PJLWC6OG0RwwEHqbZQJX_DWpDc0px6W9WnloZvMLN96AQIP2qZwZspc_y-OeyH2HbxEP54e3wvk_wjVOKOhginQkdGvzVolcpINVJAmPa_AMX75ET3lgYOdJPBoSuehhkaFU-U-bTeyVldp7YZ8DxCJSQ8DbF2gEAnq1KzwoMEu6V9jrqhbamkGyVHUP0voa916IXHsuW5vb_OAbaP_3Ns88nBp6QfEOEWkpe_s4JYv9zOjrjhLYdwE5CrQkTJjcScpm6iwOF6rJJKxr07HUe3QbcNZ2jug-ObEDS6yhDRUEvkBLIi7YGm-Y2KvNT7uevUzsa5HSPCT4miKE4

