### 测试登录
POST http://localhost:8001/auth/oauth/jwt/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 测试登录用户(auth)
GET http://localhost:8001/auth/current/user/details
Accept: application/json
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjkzNzMzOTgwLCJleHAiOjE2OTM3NTE5ODB9.JNhG98qm7tSS1nQwvNtir-DT4-tV3vptgYQH2bqeytBsyi1ToaCyKlxP0XYO2UQ5hJpG68uKQNg-HrGXp-5iVE_SFVJoSl7FPCbVtu76mH51JGTO5GoZMwhIIz3avD5GB1UxwUNcjThjbxo8bOVDA8piscosSpoEAPQtFg8jxPtG-ZOEh8iUFhAIeXOaT_GzBmbTXJBf-nMXncjsjwwkKx7mS_5LCbGOXgXVu89urGhu4bJdLbt8bBBQQKgRQ-X8K9sG0lJMzTA0tsrt1ekqUdaM61NXwYwKc_XML2ESjHfHOudV8l7ExU_eJYzAqXZlhAvZRqpHtl1A2frJcuj9Hr_kvm-wxcCY0fKjzeRDNQ7pWJ7Usdlq6uMPEnL71Qf9ruvrejzFMIrVAPL4xQDILgvaW36AkyiV5pdGh8h_QdLj2-T8eLl6F11XWJtGV48XllhT9IH8y3DV79D8AgKL6UnCMl_LZxbRjGIyhwgikXtSkYrZUHhKkxxEJXcmjcL2-5nGz1vq3GPj6Fkv9YsIf_03qR-EvHB8IOA-dA6Ne82ub5llHHExyC5TrqW22r2n9-z9clbSWtPY7-nkY2FzzOIXGIV5bdia_mBLYWPhMgJViQK7JCGsSopdLMOiI0nej3dBuuIuMBgR7vGXHiv5d8hqcPMI4OkovC7bn1vtUE8

### 测试登录用户(admin)
GET http://localhost:8002/admin/current/user/details
Accept: application/jsons
Verified-Ticket: verifiedTicket
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInVzZXJUeXBlIjoiNCIsInVzZXJJZCI6IjEiLCJhY2NvdW50IjoiYWRtaW4iLCJpc3MiOiJjb20uZ2l0aHViLml0ZGFjaGVuIiwiaWF0IjoxNjg5NDM3MTc1LCJleHAiOjE2ODk0NTUxNzV9.vaYjFMVVK95J_tm_JFhJT-sQ2F2gComiuJQzM90_6M5M0xGFvkFIxvOfXhA_isy4DGg-U8N7wh60yXPYNplk6Q3K_mrEO1ukG-xybI9Oax1zhRxZARiVkHw2wmCypkW9x2SrpvkZhBWjqwtDRHehHqCjYkN8WjBOc-K8tLcEdWkrHNnDnchAH_H3wJaj3qcS1n7Lpc_GUIHXrWuw8gmxG-azb55Olx2_mcMwgGmTAkz1coOooa4rl5DLlz8mwlOtlXHPY5I10RttVS-ZT-39kFt9BE6Uqh-tE7cyTkF5zcVKKGVMMZ8s-NvkslkgjOnHrZKMxl7cMgL-wgPukjQHMhRcvC7WYb7x35RS_grPnJomFU8HhszhQf_8z_fDWT3LJpK__pPbb96YKvltRSXejpjGtzRMwEgOpNzZAFoF8QlaLULK6EJk7L9MCnfCTPiu48g6P42EaAVxzQbG1YBZXpJ72YNEjBWY7BcHlJ_WxdBqhxfE2m6iJumUfeYx2wXEkdnDqr0MrZXwDRkEuJmuapzq5KHtroYjhF_cGfvj43pILfkJaL-dHyHqN7N_1jKt8C-DoBgCallWkRxmb3CnmIwLXkQTTh63eSpGvOUaO4N9hbzopVT_3jFgfllAMepDTUtJ1_qBg6szjmXG4hSHbhRj0T7FGhDZAM3szP1GUaw

